---
_extends: .github:common-settings.yaml

repository:
  name: .github
  description: GitHub defaults and community health files for @fro-bot.
  topics: fro-bot, actions, github-actions, renovate-config

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: [Analyze (typescript), CodeQL, Lint, Renovate, Review Dependencies]
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
        require_last_push_approval: true
      restrictions: null
      required_linear_history: true
