---
_extends: .github:common-settings.yaml

repository:
  name: .github
  description: GitHub defaults and community health files for @fro-bot.
  topics: fro-bot, actions, github-actions, renovate-config

branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: ['Lint', 'Renovate / Renovate']
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
