---
# Based on https://github.com/bfra-me/works/blob/7217b637351a0b251d1d0c2158614210c7efdad0/.github/actions/pnpm-install/action.yaml
name: Setup
description: Setup build environment and install dependencies

inputs:
  cache-version:
    default: '0'
    description: Cache version. Can be incremented to invalidate the cache.
    required: false

runs:
  steps:
    - name: Install mise
      env:
        MISE_VERSION: 2025.11.0 # renovate: datasource=github-releases packageName=jdx/mise
      uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
      with:
        version: ${{ env.MISE_VERSION }}

    - id: configure-cache
      name: Configure cache
      run: |
        if [ ! `which pnpm` ]; then
          echo "pnpm is not installed"
          exit 1
        fi
        pnpm_store_path="$(pnpm store path --silent)"
        if [ -z "$pnpm_store_path" ]; then
          echo "Failed to get pnpm store path"
          exit 1
        fi
        mkdir -p "$pnpm_store_path" || exit 1
        echo "path=$pnpm_store_path" >> $GITHUB_OUTPUT
        year_month=$(date -u '+%Y-%m')
        base_key="pnpm-store-v${{ inputs.cache-version }}-${{ runner.os }}-${year_month}-"
        echo "key=${base_key}${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
        echo "restore-keys=${base_key}" >> $GITHUB_OUTPUT
      shell: 'bash -Eeuo pipefail {0}'

    - name: Restore pnpm store cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.configure-cache.outputs.key }}
        path: ${{ steps.configure-cache.outputs.path }}
        restore-keys: ${{ steps.configure-cache.outputs.restore-keys }}

    - name: Install dependencies
      run: pnpm bootstrap
      shell: bash -Eeuo pipefail {0}

  using: composite
