# Continuous Integration jobs for changes headed to main.
---
name: Main

on:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

defaults:
  run:
    shell: bash -Eeuo pipefail {0}

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⤵ Checkout Branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.head_ref }}

      - name: 📦 Setup
        uses: ./.github/actions/setup

      - env:
          TIMING: 1
        name: 💅🏽 Lint
        run: pnpm lint

  check-types:
    name: Check Types
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⤵ Checkout Branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.head_ref }}

      - name: 📦 Setup
        uses: ./.github/actions/setup

      - name: ✅ Validate Types
        run: pnpm check-types

  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⤵ Checkout Branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.head_ref }}

      - name: 📦 Setup
        uses: ./.github/actions/setup

      - name: 🧪 Run Tests
        run: pnpm test

  check-workflows:
    name: Check Workflows
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⤵ Checkout Branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.head_ref }}

      - name: 📦 Setup
        uses: ./.github/actions/setup

      - name: ✅ Validate Workflows
        uses: rhysd/actionlint@e7d448ef7507c20fc4c88a95d0c448b848cd6127 # v1.7.8
