---
name: Manage Cache

on:
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00
  workflow_dispatch:
    inputs:
      ref:
        description: The ref where cache entries should be deleted
        type: string

permissions:
  contents: read

env:
  REF: >-
    ${{
      github.event_name == 'pull_request' && github.event.pull_request.merged && format('refs/pull/{0}/merge', github.event.pull_request.number)
      || inputs.ref
      || github.event_name != 'pull_request' && github.ref
      || ''
    }}

jobs:
  cleanup-cache:
    name: Cleanup cache
    runs-on: ubuntu-latest
    steps:
      - if: env.REF != ''
        id: get-workflow-app-token
        name: Get Workflow Access Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - if: env.REF != ''
        name: Deleting workflow caches on ${{ env.REF }}
        env:
          GH_TOKEN: ${{ steps.get-workflow-app-token.outputs.token }}
        run: |
          CACHE_KEYS="$(gh cache list -R "${{ github.repository }}" --ref "${{ env.REF }}" --limit 100 --order asc --sort last_accessed_at | cut -f 2 | tr '\n' ' ')"
          for key in $CACHE_KEYS; do
            gh cache delete "$key" -R "${{ github.repository }}"
          done

  setup-cache:
    if: github.event_name != 'pull_request'
    name: Setup cache
    runs-on: ubuntu-latest
    steps:
      - name: ⤵ Checkout Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.REF }}

      - name: 📦 Setup
        uses: ./.github/actions/setup
