name: Sync Settings

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/settings.yml'
      - '.github/workflows/sync-settings.yaml'
  schedule:
    - cron: '55 2 * * *'

permissions: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: 'administration:write, contents:read, issues:write, members:write'

      - name: Sync Settings to GitHub
        uses: exivity/actions/sync-defaults@main
        with:
          gh-token: ${{ steps.get_workflow_token.outputs.token }}
